version: '3'

services:
    deluge-daemon:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: deluge
        env_file:
            - .env
        command: /daemon-entry.sh
        network_mode: deluge:openvpn-client
        ports:
            - 58846:58846
            - 6881
            - 6891
    deluge-web:
        image: deluge
        command: deluge-web -c /config -p 80
        ports:
            - 9980:80
